const swaggerJsdoc = require('swagger-jsdoc');
const options = {
    //List of files to be processed
    apis: ['./server.js', './models/user.js'],

    basePath: '/',
    host: 'localhost:3000',
    swaggerDefinition: { info: { description: 'API with autogenerated swagger doc', swagger: '2.0', title: 'ToDo API', version: '1.0.0', }, },
};


const specs = swaggerJsdoc(options);
module.exports = { specs };